// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoRepositories;

#nullable disable

namespace TodoRepositories.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20260409152530_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("TodoRepositories.Entity.TodoItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20b3ff4d-ee8e-414d-823f-65ae3600e2af"),
                            CreatedDate = new DateTime(2026, 4, 9, 15, 25, 27, 39, DateTimeKind.Utc).AddTicks(737),
                            Title = "First dummy todo",
                            isCompleted = false
                        },
                        new
                        {
                            Id = new Guid("58e50c68-460e-40f2-a2df-792b1cf17d4c"),
                            CreatedDate = new DateTime(2026, 4, 9, 15, 25, 27, 39, DateTimeKind.Utc).AddTicks(1122),
                            Title = "Second dummy todo",
                            isCompleted = false
                        },
                        new
                        {
                            Id = new Guid("5d5794cc-8d91-4a32-bc8c-2f9b72b9faa3"),
                            CreatedDate = new DateTime(2026, 4, 9, 15, 25, 27, 39, DateTimeKind.Utc).AddTicks(1130),
                            Title = "Third dummy todo",
                            isCompleted = true
                        },
                        new
                        {
                            Id = new Guid("ada242e8-f933-421e-bcca-49fdcff41096"),
                            CreatedDate = new DateTime(2026, 4, 9, 15, 25, 27, 39, DateTimeKind.Utc).AddTicks(1134),
                            Title = "Fourth dummy todo",
                            isCompleted = false
                        },
                        new
                        {
                            Id = new Guid("ddb976e7-9344-4533-95de-ebcb71bbd969"),
                            CreatedDate = new DateTime(2026, 4, 9, 15, 25, 27, 39, DateTimeKind.Utc).AddTicks(1138),
                            Title = "Fifth dummy todo",
                            isCompleted = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
