name: Build & Test 🧪

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '10.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
  
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Restore dependencies 📂
        run: dotnet restore

      - name: Build 🧱
        run: dotnet build --configuration Release --no-restore

      - name: Test 🧪
        run: dotnet test --configuration Release --no-build

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/test-results/**/*.xml'

      - name: Publish 🚀
        run: dotnet publish TodoApi -c Release -o ./publish

      - uses: actions/upload-artifact@v4
        with:
          name: todoapi
          path: ./publish
          
